signin_xpath = "(//button)[2]"
signin2_xpath ="(//div[@aria-label='Connexion'])[1]"
apply_button_path = "(//a[normalize-space()='Apply'])[1]"
use_last_button_path = "(//a[normalize-space()='Use My Last Application'])[1]"
how_hear_path = "//button[@id='input-1']"
career_website_button_path = "(//div[normalize-space()='Airbus Careers Website'])[1]"
save_cont_path = "(//button[normalize-space()='Save and Continue'])[1]"
submit = "(//button[normalize-space()='Submit'])[1]"
semester_level_path = "(//textarea[@id='input-274'])[1]"
uni_name_path = "(//textarea[@id='input-276'])[1]"
course_path = "(//textarea[@id='input-278'])[1]"
finish_studies = "(//textarea[@id='input-280'])[1]"

contract_type = "(//button[@id='input-282'])[1]"
drop_dwn_path = "(//div[contains(text(),'Full-time internship as part of an academic initia')])[1]"
third_part_financ = "(//textarea[@id='input-284'])[1]"
mand = "(//input[@id='33411a05eded01123b4a08bf026644cc'])[1]"
availb = "(//textarea[@id='input-288'])[1]"
dur_int = "(//textarea[@id='input-290'])[1]"

eng_rate="(//button[@id='input-292'])[1]"
fluent = "(//div[normalize-space()='Negotiation / Fluent'])[1]"

fen_rate="(//button[@id='input-294'])[1]"
intm = "(//div[normalize-space()='Intermediate'])[1]"

gend = "(//button[@id='input-295'])[1]"
male = "(//div[normalize-space()='Male'])[1]"
bd = "(//div[@id='input-298-dateSectionMonth-display'])[1]"
nation = "(//button[@id='input-299'])[1]"
liban = "(//div[contains(text(),'Lebanon')])[1]"
add_nat = "(//input[@id='input-300'])[1]"
accept = "(//input[@id='input-301'])[1]"
